### ISSUE TITLE
搜索时候如何忽略大小写

### ISSUE THREAD

**Issue by lycclsltt** [hnzzmsf/layui-formSelects#26]
搜索时候如何忽略大小写

**Comment by osashiburi** [comment]
> 搜索时候如何忽略大小写

我也想问这个来着，请问你解决了吗？

**Comment by rain001** [comment]
你们解决了么？

**Comment by rain001** [comment]
插件在搜索的时候未统一大小写后再进行搜索，找到比较的地方将下拉值与Input的值统一成大写或者小写
![image](https://user-images.githubusercontent.com/25876371/222670634-9c1c384c-c3b3-450b-9819-2b19b229b693.png)
